CREATE TABLE TRANSACTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(64),
    DEPOSIT BIGINT,
    WITHDRAW BIGINT,
    CURRENCY VARCHAR(3),
    DATE TIMESTAMP
);

CREATE TABLE BALANCE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(64),
    BALANCE BIGINT,
    CURRENCY VARCHAR(3),
    MODIFIED TIMESTAMP,
    LAST_TRANSACTION_ID BIGINT
);

ALTER TABLE BALANCE ADD FOREIGN KEY (LAST_TRANSACTION_ID) REFERENCES TRANSACTION(ID);