# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.16
    container_name: mysql-db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    #volumes:
      #- local-path-dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 33306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080