spring:
  application:
    name: wallet-client

grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    com: DEBUG
